version: 0.0
os: linux
files:
  - source: /server
    destination: /home/ec2-user/api
hooks:
  Beforeinstall:
    - location: scripts/delete_module.sh
      runas: ec2-user
      timeout: 60
  AfterInstall:
    - location: scripts/npm_install.sh
      runas: ec2-user
      timeout: 300
  ApplicationStart:
    - location: scripts/npm_start.sh
      runas: ec2-user
      timeout: 60
  ApplicationStop:
    - location: scripts/npm_stop.sh
      runas: ec2-user
      timeout: 300
