version: 0.0
os: linux
files:
  - source: /server
    destination: /home/ubuntu/filedrop-api-nodejs
hooks:
  AfterInstall:
    - location: scripts/npm_install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/npm_start.sh
      runas: root
      timeout: 60
  ApplicationStop:
    - location: scripts/npm_stop.sh
      runas: root
      timeout: 300
